# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mahafuzur Portfolio
email: mahafuzurrahaman1986@gmail.com
description: "This is a portfolio site with jekyll and hosted in cloudcanon."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mahafuzur.tk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mahafuzur
github_username:  mahafuzur
collections:
  projects:
    output: true
# Build settings
markdown: kramdown
plugins: [jekyll-paginate, jekyll-github-metadata, jekyll-feed]
excerpt_separator: <!--more-->
paginate: 4
paginate_path: '/blog/page:num/'
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: blog/:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
